name: Preprocessing Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7
      - name: Install dependencies
        run: |
          pip install pandas scikit-learn joblib
      - name: Run preprocessing
        run: python preprocessing/automate_Selly-Supriyatin.py
      - name: Upload preprocessed data as artifact
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed_data
          path: preprocessed_data/